sudo: false
language: java

jdk:
  - oraclejdk8
  - oraclejdk9

env:
  - TERM=dumb

cache:
  directories:
  - $HOME/.gradle

before_install:
#  - rm -r ~/.gradle/caches
  - git clone https://github.com/huxi/sulky.git ~/builds/sulky
  - pushd ~/builds/sulky
  - git checkout $TRAVIS_BRANCH
  - ./gradlew --stacktrace install
  - popd

script:
  - ./gradlew --stacktrace

after_success:
  - ./gradlew --stacktrace cleanTest
  - ./gradlew --stacktrace jacocoRootReport
  - ./gradlew --stacktrace coveralls
  - bash <(curl -s https://codecov.io/bash)
